### ISSUE TITLE
Duplicate ICashRegister

### ISSUE THREAD

**Issue by dertseha** [paulroho/SupermarketKata#1]
There is
* [ICashRegister.cs](https://github.com/paulroho/SupermarketKata/blob/331505d37872599de3da04e33c012981467ab2c1/CSharp/Supermarket/Model/Checkout/ICashRegister.cs)
* [CashRegister.cs](https://github.com/paulroho/SupermarketKata/blob/4659643530bdef77161f6ad4c648b0c1e175b554/CSharp/Supermarket/Model/Checkout/CashRegister.cs)
Both containing an ICashRegister interface.

The recent commit of CashRegister.cs notes a removal of API hints.
Which was the intention - removal of ICashRegister from CashRegister.cs or removal of ICashRegister.cs ?

Apart from that: why does this work at all? (I haven't checked whether ICashRegister.cs is in the project.)

**Comment by paulroho** [comment]
You're right, the ICashRegister.cs should not be there, since the interface is now defined in CashRegister.cs. But note, this is not a problem for the compilation because ICashRegister.cs is not referenced from within the project file.
